import { describe, test, expect } from '@jest/globals';

const parser = await import('#app/infrastructure/parsers/cargoLockParser.js');
const { findParsersForFile } = await import('#app/infrastructure/parsers/parserRegistry.js');
const { compareVersions, lowerVersion } = await import('#app/infrastructure/parsers/pickVersion.js');

// Trimmed from rust-lang/cargo's own lockfile, which has 550 [[package]]
// blocks: 523 from a registry, 27 workspace members with no source at all, and
// 23 crate names appearing at more than one version.
const CARGO_LOCK = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "adler2"
version = "2.0.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "320119579fcad9c21884f5c4861d16174d0e06250625266f50fe6898340abefa"

[[package]]
name = "aho-corasick"
version = "1.1.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ddd31a130427c27518df266943a5308ed92d4b226cc639f5a8f1002816174301"
dependencies = [
 "memchr",
]

[[package]]
name = "bitflags"
version = "2.13.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "fake"

[[package]]
name = "bitflags"
version = "1.3.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "fake"

[[package]]
name = "memchr"
version = "2.7.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "fake"

[[package]]
name = "patched-upstream"
version = "0.5.0"
source = "git+https://github.com/someone/patched-upstream.git?branch=main#aabbcc"

[[package]]
name = "cargo"
version = "0.94.0"
dependencies = [
 "aho-corasick",
 "bitflags",
]

[[package]]
name = "benchsuite"
version = "0.0.0"
`;

const read = content =>
    Object.fromEntries(parser.parse(content, 'Cargo.lock').map(d => [d.name, d.version]));

describe('discovery', () => {
    test.each([
        ['Cargo.lock', 1],
        ['crates/api/Cargo.lock', 1],
        ['Cargo.toml', 1],
    ])('%s matches %i parser(s)', (filePath, expected) => {
        expect(findParsersForFile(filePath)).toHaveLength(expected);
    });

    test('it states resolved versions, so its rows win over Cargo.toml', () => {
        expect(parser.resolvesVersions).toBe(true);
    });
});

describe('Cargo.lock', () => {
    const deps = read(CARGO_LOCK);

    test('reads a registry crate at its resolved version', () => {
        expect(deps['adler2']).toBe('2.0.1');
        expect(deps['memchr']).toBe('2.7.4');
    });

    // A crate with no source key is a member of this workspace: the
    // repository's own code, which no CVE can match and crates.io knows
    // nothing about. cargo has 27 of them.
    test.each(['cargo', 'benchsuite'])('%s is a workspace member, not a dependency', name => {
        expect(deps).not.toHaveProperty(name);
    });

    test('a git source is a dependency with no comparable version', () => {
        expect(deps).toHaveProperty('patched-upstream');
        expect(deps['patched-upstream']).toBeNull();
    });

    // A crate's dependencies list is an array of indented strings naming crates
    // that each have a [[package]] block of their own.
    test('the dependencies array is not packages', () => {
        expect(Object.keys(deps).sort()).toEqual([
            'adler2',
            'aho-corasick',
            'bitflags',
            'memchr',
            'patched-upstream',
        ]);
    });

    // If 1.3.2 is vulnerable and 2.13.0 is patched, keeping the newer one turns
    // a real exposure into a row that reads as clean. 23 crates in cargo's own
    // lockfile are in this position.
    test('a crate at two versions keeps the lower one', () => {
        expect(deps['bitflags']).toBe('1.3.2');
    });

    test('the file version key at the top is not a package', () => {
        expect(deps).not.toHaveProperty('version');
    });
});

describe('picking between two versions', () => {
    test.each([
        ['1.3.2', '2.13.0', '1.3.2'],
        ['0.4.3', '0.2.17', '0.2.17'],
        ['0.16.1', '0.14.5', '0.14.5'],
        // Numeric segments compare as numbers, or 10 would sort before 9.
        ['1.9.0', '1.10.0', '1.9.0'],
        ['1.0.0-beta', '1.0.0-rc', '1.0.0-beta'],
    ])('%s against %s keeps %s', (a, b, expected) => {
        expect(lowerVersion(a, b)).toBe(expected);
        expect(lowerVersion(b, a)).toBe(expected);
    });

    // An unknown version cannot be compared against a registry, so it says
    // nothing about exposure while a real one does.
    test('a known version beats an unknown one', () => {
        expect(lowerVersion(null, '1.0.0')).toBe('1.0.0');
        expect(lowerVersion('1.0.0', null)).toBe('1.0.0');
    });

    test('two unknowns stay unknown', () => {
        expect(lowerVersion(null, null)).toBeNull();
    });

    test('equal versions compare as equal', () => {
        expect(compareVersions('1.2.3', '1.2.3')).toBe(0);
    });
});

describe('what must not throw', () => {
    test.each([
        ['an empty file', ''],
        ['only the file version', 'version = 4\n'],
        ['a package with no name', '[[package]]\nversion = "1.0"\n'],
        ['a package with no version', '[[package]]\nname = "x"\nsource = "registry+https://x"\n'],
    ])('%s', (_label, content) => {
        expect(() => parser.parse(content, 'Cargo.lock')).not.toThrow();
    });

    test('a crate with no version reports unknown rather than being dropped', () => {
        const deps = read('[[package]]\nname = "x"\nsource = "registry+https://x"\n');

        expect(deps).toEqual({ x: null });
    });
});
