import { describe, test, expect } from '@jest/globals';

const haskell = await import('#app/infrastructure/parsers/haskellParser.js');
const lock = await import('#app/infrastructure/parsers/haskellLockParser.js');
const { findParsersForFile } = await import('#app/infrastructure/parsers/parserRegistry.js');
const { Ecosystem } = await import('#app/domain/enums/Ecosystem.js');
const { supportsEcosystem } = await import('#app/infrastructure/registries/index.js');

// Trimmed from jgm/pandoc. The two stanzas below are the shapes that matter: one
// whose next field sits at exactly the keyword's indent, and one whose list wraps.
const PANDOC_CABAL = `name:            pandoc
version:         3.6
build-type:      Simple
cabal-version:   2.4

library
  import:        common-options
  build-depends: base                  >= 4.18      && < 5,
                 text                  >= 1.1.1.0   && < 2.2,
                 containers            >= 0.6.0.1   && < 0.9
  hs-source-dirs:  src
  exposed-modules: Text.Pandoc

executable pandoc
  build-depends:    pandoc
  ghc-options:      -rtsopts -with-rtsopts=-A8m -threaded
                    -Wincomplete-record-updates
                    -Widentities

test-suite test-pandoc
  build-depends: pandoc,
                 tasty                 >= 1.4       && < 1.6
  -- a comment
  hs-source-dirs: test
`;

// Trimmed from jgm/pandoc. The list items sit at column zero, level with the key.
const STACK_YAML = `flags:
  pandoc:
    embed_data_files: true
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-server'
extra-deps:
- hslua-2.5.0
- hslua-module-doclayout-1.2.1.1
- git: https://github.com/someone/thing.git
  commit: aabbccddeeff
resolver: lts-23.2
`;

// Trimmed from hasura/graphql-engine. The list wraps and includes flag
// constraints alongside the version pins.
const CABAL_FREEZE = `active-repositories: hackage.haskell.org:merge
constraints: any.Cabal ==3.16.0.0,
             any.aeson ==2.2.5.0,
             aeson -cffi +ordered-keymap,
             any.indexed-traversable ==0.1.4,
             any.text ==2.1.1
index-state: hackage.haskell.org 2026-06-01T12:22:50Z
`;

const STACK_LOCK = `# This file was autogenerated by Stack.
packages:
- completed:
    hackage: hslua-2.5.0@sha256:0f7a1e2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7,4567
    pantry-tree:
      sha256: aabbcc
      size: 1234
  original:
    hackage: hslua-2.5.0
snapshots:
- completed:
    sha256: ddeeff
    size: 640030
    url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/23/2.yaml
  original: lts-23.2
`;

const read = (parser, content, file) =>
    Object.fromEntries(parser.parse(content, file).map(d => [d.name, d.version]));

describe('the ecosystem', () => {
    test('HACKAGE is declared, and Hackage answers about it', () => {
        expect(Ecosystem.HACKAGE).toBe('HACKAGE');
        expect(supportsEcosystem('HACKAGE')).toBe(true);
    });
});

describe('discovery', () => {
    test.each([
        ['pandoc.cabal', 1],
        ['stack.yaml', 1],
        ['cabal.project.freeze', 1],
        ['stack.yaml.lock', 1],
        ['lib/thing.cabal', 1],
        ['cabal.project', 0],
    ])('%s matches %i parser(s)', (filePath, expected) => {
        expect(findParsersForFile(filePath)).toHaveLength(expected);
    });

    test('only the lock files resolve versions', () => {
        expect(lock.resolvesVersions).toBe(true);
        expect(haskell.resolvesVersions).toBeUndefined();
    });
});

describe('a .cabal file', () => {
    const deps = read(haskell, PANDOC_CABAL, 'pandoc.cabal');

    test('reads a wrapped build-depends list', () => {
        expect(deps['base']).toBe('>= 4.18      && < 5');
        expect(deps['text']).toBe('>= 1.1.1.0   && < 2.2');
        expect(deps['containers']).toBe('>= 0.6.0.1   && < 0.9');
    });

    test('every stanza contributes', () => {
        expect(deps['tasty']).toBe('>= 1.4       && < 1.6');
    });

    test('a dependency with no constraint is unknown, not missing', () => {
        expect(Object.keys(deps)).toContain('pandoc');
        expect(deps['pandoc']).toBeNull();
    });

    // pandoc has a stanza where the next field, ghc-options:, sits at exactly the
    // build-depends indent — so the list ends by comparing against the keyword's
    // own indentation rather than by counting spaces.
    test('the field after the list is not a dependency', () => {
        expect(deps).not.toHaveProperty('hs-source-dirs');
        expect(deps).not.toHaveProperty('ghc-options');
    });

    // ghc-options wraps too, and its continuation lines are indented deeper than
    // the build-depends above them.
    test('a wrapped ghc-options block is not dependencies', () => {
        expect(Object.keys(deps).sort()).toEqual([
            'base',
            'containers',
            'pandoc',
            'tasty',
            'text',
        ]);
    });
});

describe('a stack.yaml', () => {
    const deps = read(haskell, STACK_YAML, 'stack.yaml');

    // Stack writes list items at column zero, level with their key: `extra-deps:`
    // and `- hslua-2.5.0` are both unindented. Treating an unindented line as a
    // new section read nothing at all out of pandoc's real file.
    test('reads extra-deps whose items are level with the key', () => {
        expect(deps['hslua']).toBe('2.5.0');
    });

    // Hackage names contain dashes, so the split is at the last dash a digit
    // follows.
    test('a dashed name keeps its dashes', () => {
        expect(deps['hslua-module-doclayout']).toBe('1.2.1.1');
    });

    describe('what is not an extra-dep', () => {
        // packages: lists the project's own local packages.
        test.each(["'.'", "'pandoc-cli'", "'pandoc-server'"])('%s under packages', name => {
            expect(Object.keys(deps)).not.toContain(name);
        });

        // resolver: names an LTS set, and nothing in the repository resolves it.
        test('the resolver', () => {
            expect(deps).not.toHaveProperty('resolver');
            expect(Object.keys(deps)).not.toContain('lts-23.2');
        });

        // A git extra-dep is an object across several lines.
        test('the keys of a git extra-dep', () => {
            expect(deps).not.toHaveProperty('commit');
            expect(Object.keys(deps)).toHaveLength(2);
        });
    });
});

describe('cabal.project.freeze', () => {
    const deps = read(lock, CABAL_FREEZE, 'cabal.project.freeze');

    test('reads a pin, with or without the any. prefix', () => {
        expect(deps['Cabal']).toBe('3.16.0.0');
        expect(deps['aeson']).toBe('2.2.5.0');
        expect(deps['text']).toBe('2.1.1');
    });

    // `aeson -cffi +ordered-keymap` names a package and sets build flags. It is
    // in the same comma-separated list and pins nothing.
    test('a flag constraint is not a version', () => {
        expect(deps['aeson']).toBe('2.2.5.0');
        expect(Object.values(deps).some(version => version.includes('cffi'))).toBe(false);
    });

    test("the file's own settings are not packages", () => {
        expect(Object.keys(deps).sort()).toEqual([
            'Cabal',
            'aeson',
            'indexed-traversable',
            'text',
        ]);
    });
});

describe('stack.yaml.lock', () => {
    const deps = read(lock, STACK_LOCK, 'stack.yaml.lock');

    // The same hackage: line appears twice per extra-dep — once under completed:
    // with a hash and once under original: without.
    test('reads a pin once, with the hash cut off', () => {
        expect(deps).toEqual({ hslua: '2.5.0' });
    });

    // snapshots: pins the LTS set itself by URL and hash.
    test('the snapshot is not a package', () => {
        expect(deps).not.toHaveProperty('lts-23.2');
        expect(deps).not.toHaveProperty('pantry-tree');
    });
});

describe('what must not throw', () => {
    test.each([
        [haskell, 'x.cabal', 'name: x\nversion: 1.0\n'],
        [haskell, 'x.cabal', ''],
        [haskell, 'stack.yaml', 'resolver: lts-23.2\n'],
        [lock, 'cabal.project.freeze', 'index-state: hackage.haskell.org 2026-01-01T00:00:00Z\n'],
        [lock, 'stack.yaml.lock', 'snapshots: []\n'],
    ])('%#', (parser, file, content) => {
        expect(parser.parse(content, file)).toEqual([]);
    });
});
