import { describe, test, expect } from '@jest/globals';

const parser = await import('#app/infrastructure/parsers/npmLockParser.js');
const { findParsersForFile } = await import('#app/infrastructure/parsers/parserRegistry.js');

/**
 * The four npm-family lockfiles.
 *
 * Each fixture is trimmed from a real file — npm/cli, vuejs/core, facebook/react
 * and oven-sh/bun — because these shapes are unusual enough that a hand-written
 * sample proves nothing. Two of the tests below exist only because a real file
 * disagreed with what the format looked like it did.
 */

const read = (content, file) =>
    Object.fromEntries(parser.parse(content, file).map(d => [d.name, d.version]));

// package-lock.json version 3: packages keyed by install path.
const NPM_V3 = JSON.stringify({
    name: 'npm',
    version: '11.0.0',
    lockfileVersion: 3,
    requires: true,
    packages: {
        '': { name: 'npm', version: '11.0.0', workspaces: ['docs', 'workspaces/*'] },
        docs: { name: '@npmcli/docs', version: '1.0.0' },
        'node_modules/@npmcli/docs': { resolved: 'docs', link: true },
        'node_modules/lodash': {
            version: '4.17.21',
            resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
            integrity: 'sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==',
        },
        'docs/node_modules/entities': { version: '6.0.1' },
        'node_modules/@babel/core': { version: '7.26.0' },
        'node_modules/a/node_modules/b': { version: '1.0.0' },
    },
});

// package-lock.json version 1: dependencies nested by name.
const NPM_V1 = JSON.stringify({
    name: 'old-app',
    lockfileVersion: 1,
    dependencies: {
        lodash: { version: '4.17.15', resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz' },
        chalk: {
            version: '2.4.2',
            dependencies: {
                'ansi-styles': { version: '3.2.1' },
            },
        },
    },
});

// pnpm-lock.yaml version 9. importers: above and snapshots: below name the same
// packages again, and reading either would double every row.
const PNPM_V9 = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:

  .:
    dependencies:
      '@vue/shared':
        specifier: workspace:*
        version: link:packages/shared
      lodash:
        specifier: ^4.17.0
        version: 4.17.21

packages:

  '@babel/code-frame@7.29.0':
    resolution: {integrity: sha512-fake==}
    engines: {node: '>=6.9.0'}

  lodash@4.17.21:
    resolution: {integrity: sha512-fake==}

  vue@3.5.13:
    resolution: {integrity: sha512-fake==}
    peerDependencies:
      typescript: '*'

snapshots:

  '@babel/code-frame@7.29.0': {}

  lodash@4.17.21: {}

  vue@3.5.13(typescript@5.6.3): {}
`;

// pnpm before version 6 put the version after a slash, not an @.
const PNPM_V5 = `lockfileVersion: 5.4

packages:

  /lodash/4.17.21:
    resolution: {integrity: sha512-fake==}
    dev: false

  /@babel/core/7.26.0:
    resolution: {integrity: sha512-fake==}
    dev: true
`;

// yarn.lock classic, from facebook/react. One header can carry several
// specifiers for one resolved package.
const YARN_CLASSIC = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@ampproject/remapping@^2.1.0", "@ampproject/remapping@^2.2.0":
  version "2.3.0"
  resolved "https://registry.yarnpkg.com/@ampproject/remapping/-/remapping-2.3.0.tgz#ed441b6"
  integrity sha512-fake==
  dependencies:
    "@jridgewell/gen-mapping" "^0.3.5"

lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c5"
  integrity sha512-fake==

"local-thing@file:../local-thing":
  version "1.0.0"
`;

// yarn.lock from Berry: YAML, and the version is not quoted.
const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0/fake

"@babel/core@npm:^7.26.0":
  version: 7.26.0
  resolution: "@babel/core@npm:7.26.0"
`;

// bun.lock, from oven-sh/bun. JSONC, one entry per line, and a workspace
// version whose path holds a scope.
const BUN = `{
  "lockfileVersion": 1,
  "workspaces": {
    "": {
      "name": "bun",
      "devDependencies": {
        "esbuild": "^0.21.5",
        "@types/bun": "workspace:*"
      }
    }
  },
  "packages": {
    "@esbuild/darwin-arm64": ["@esbuild/darwin-arm64@0.21.5", "", { "os": "darwin" }, "sha512-fake=="],

    "@types/bun": ["@types/bun@workspace:packages/@types/bun"],

    "esbuild": ["esbuild@0.21.5", "", { "optionalDependencies": {} }, "sha512-fake=="],

    "mitata": ["mitata@0.1.14", "", {}, "sha512-fake=="],
  }
}
`;

describe('discovery', () => {
    test.each([
        ['package-lock.json', 1],
        ['npm-shrinkwrap.json', 1],
        ['pnpm-lock.yaml', 1],
        ['yarn.lock', 1],
        ['bun.lock', 1],
        ['apps/web/package-lock.json', 1],
        // A custom serialised format, not text. See docs/repositories.md.
        ['bun.lockb', 0],
    ])('%s matches %i parser(s)', (filePath, expected) => {
        expect(findParsersForFile(filePath)).toHaveLength(expected);
    });

    test('it states resolved versions, so its rows win over package.json', () => {
        expect(parser.resolvesVersions).toBe(true);
    });
});

describe('package-lock.json, version 3', () => {
    const deps = read(NPM_V3, 'package-lock.json');

    test('reads the resolved version', () => {
        expect(deps['lodash']).toBe('4.17.21');
    });

    test('a scoped package keeps its scope', () => {
        expect(deps['@babel/core']).toBe('7.26.0');
    });

    // Most of an npm tree is transitive and a CVE does not care how a package
    // arrived, so a nested install path is still a dependency.
    test('a nested install path gives the innermost name', () => {
        expect(deps['b']).toBe('1.0.0');
    });

    test('a workspace package has its own node_modules read', () => {
        expect(deps['entities']).toBe('6.0.1');
    });

    describe('what is not a dependency', () => {
        test('the project itself, keyed by the empty string', () => {
            expect(deps).not.toHaveProperty('npm');
        });

        test('a workspace package in the repository', () => {
            expect(deps).not.toHaveProperty('@npmcli/docs');
        });

        test('no name carries a node_modules prefix', () => {
            expect(Object.keys(deps).some(name => name.includes('node_modules'))).toBe(false);
        });
    });
});

describe('package-lock.json, version 1', () => {
    const deps = read(NPM_V1, 'package-lock.json');

    test('reads the nested dependencies map', () => {
        expect(deps['lodash']).toBe('4.17.15');
        expect(deps['chalk']).toBe('2.4.2');
    });

    test('a dependency of a dependency counts', () => {
        expect(deps['ansi-styles']).toBe('3.2.1');
    });
});

describe('pnpm-lock.yaml', () => {
    const deps = read(PNPM_V9, 'pnpm-lock.yaml');

    test('reads the packages section', () => {
        expect(deps).toMatchObject({
            '@babel/code-frame': '7.29.0',
            lodash: '4.17.21',
            vue: '3.5.13',
        });
    });

    // importers: names the workspace's own constraints, snapshots: repeats every
    // package with its resolved peers. Either would double the rows.
    test('importers and snapshots are not read twice', () => {
        expect(Object.keys(deps)).toHaveLength(3);
        expect(deps).not.toHaveProperty('@vue/shared');
    });

    test('a peer suffix is not part of the version', () => {
        expect(deps['vue']).toBe('3.5.13');
    });

    test('version 5 separated the version with a slash', () => {
        expect(read(PNPM_V5, 'pnpm-lock.yaml')).toEqual({
            lodash: '4.17.21',
            '@babel/core': '7.26.0',
        });
    });
});

describe('yarn.lock', () => {
    test('classic: several specifiers for one package are one row', () => {
        const deps = read(YARN_CLASSIC, 'yarn.lock');

        expect(deps['@ampproject/remapping']).toBe('2.3.0');
        expect(deps['lodash']).toBe('4.17.21');
    });

    // The dependencies: block under an entry lists constraints, not resolutions.
    test('classic: a nested dependencies block is not a row', () => {
        const deps = read(YARN_CLASSIC, 'yarn.lock');

        expect(deps).not.toHaveProperty('@jridgewell/gen-mapping');
    });

    test('classic: a file: specifier has no published version', () => {
        expect(read(YARN_CLASSIC, 'yarn.lock')['local-thing']).toBeNull();
    });

    test('Berry: the version is not quoted', () => {
        const deps = read(YARN_BERRY, 'yarn.lock');

        expect(deps).toMatchObject({ lodash: '4.17.21', '@babel/core': '7.26.0' });
    });

    test('Berry: __metadata is not a package', () => {
        expect(read(YARN_BERRY, 'yarn.lock')).not.toHaveProperty('__metadata');
    });
});

describe('bun.lock', () => {
    const deps = read(BUN, 'bun.lock');

    test('reads a package', () => {
        expect(deps['esbuild']).toBe('0.21.5');
        expect(deps['mitata']).toBe('0.1.14');
    });

    test('a scoped package keeps its scope', () => {
        expect(deps['@esbuild/darwin-arm64']).toBe('0.21.5');
    });

    // Bun writes `@types/bun@workspace:packages/@types/bun`. Splitting that at
    // the last @ produced a name and a version that were both nonsense.
    test('a workspace version whose path holds a scope', () => {
        expect(deps).toHaveProperty('@types/bun');
        expect(deps['@types/bun']).toBeNull();
    });

    test('the workspaces block is not packages', () => {
        expect(Object.keys(deps).sort()).toEqual([
            '@esbuild/darwin-arm64',
            '@types/bun',
            'esbuild',
            'mitata',
        ]);
    });
});

describe('what must not throw', () => {
    test.each([
        ['package-lock.json', 'not json at all'],
        ['package-lock.json', '{}'],
        ['pnpm-lock.yaml', "lockfileVersion: '9.0'\n"],
        ['yarn.lock', '# yarn lockfile v1\n'],
        ['bun.lock', '{ "lockfileVersion": 1 }\n'],
    ])('%s: %s', (file, content) => {
        expect(parser.parse(content, file)).toEqual([]);
    });
});
