import { describe, test, expect } from '@jest/globals';

const parser = await import('#app/infrastructure/parsers/pipLockParser.js');
const { findParsersForFile } = await import('#app/infrastructure/parsers/parserRegistry.js');
const { normalizePythonName } = await import('#app/infrastructure/parsers/pythonNames.js');

/**
 * The four Python lockfiles.
 *
 * Fixtures trimmed from Textualize/rich, astral-sh/uv, pdm-project/pdm and
 * pypa/pipenv. Poetry, uv and PDM all write TOML `[[package]]` arrays, and the
 * trap they share is the sub-tables underneath each one.
 */

const read = (content, file) =>
    Object.fromEntries(parser.parse(content, file).map(d => [d.name, d.version]));

const POETRY = `# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.

[[package]]
name = "appnope"
version = "0.1.4"
description = "Disable App Nap on macOS >= 10.9"
optional = true
python-versions = ">=3.6"
groups = ["main"]
markers = "extra == \\"jupyter\\" and sys_platform == \\"darwin\\""
files = [
    {file = "appnope-0.1.4-py2.py3-none-any.whl", hash = "sha256:fake"},
]

[[package]]
name = "typing_extensions"
version = "4.12.2"
description = "Backported typing hints"
optional = false
python-versions = ">=3.8"

[[package]]
name = "ipywidgets"
version = "8.1.5"
description = "Jupyter interactive widgets"
optional = true
python-versions = ">=3.7"

[package.dependencies]
comm = ">=0.1.3"
ipython = ">=6.1.0"
traitlets = ">=4.3.1"

[[package]]
name = "forked-lib"
version = "2.0.0"
description = "A library taken from git"
optional = false
python-versions = "*"

[package.source]
type = "git"
url = "https://github.com/someone/forked-lib.git"
reference = "main"
resolved_reference = "abc123"

[[package]]
name = "local-thing"
version = "0.1.0"
description = "Something in this repository"
optional = false
python-versions = "*"

[package.source]
type = "directory"
url = "../local-thing"

[metadata]
lock-version = "2.0"
python-versions = ">=3.9.0"
content-hash = "fake"
`;

// uv states the source inline, and writes its own project as editable.
const UV = `version = 1
revision = 3
requires-python = ">=3.9"

[[package]]
name = "uv"
version = "0.9.7"
source = { editable = "." }

[package.metadata]
requires-dist = [{ name = "anyio", specifier = ">=4.0" }]

[[package]]
name = "anyio"
version = "4.13.0"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "idna" },
    { name = "sniffio" },
]
sdist = { url = "https://files.pythonhosted.org/packages/fake/anyio-4.13.0.tar.gz", hash = "sha256:fake", size = 213 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/fake/anyio-4.13.0-py3-none-any.whl", hash = "sha256:fake", size = 100 },
]

[[package]]
name = "idna"
version = "3.10"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "from-git"
version = "1.0.0"
source = { git = "https://github.com/someone/from-git.git?rev=main#abc123" }
`;

const PDM = `# This file is @generated by PDM.
# It is not intended for manual editing.

[metadata]
groups = ["default", "test"]
lock_version = "4.5.0"
content_hash = "sha256:fake"

[[package]]
name = "anyio"
version = "4.13.0"
requires_python = ">=3.10"
summary = "High-level concurrency and networking framework"
groups = ["default", "test"]
dependencies = [
    "idna>=2.8",
    "sniffio>=1.1",
]
files = [
    {file = "anyio-4.13.0-py3-none-any.whl", hash = "sha256:fake"},
]

[[package]]
name = "arpeggio"
version = "2.0.3"
summary = "Packrat parser interpreter"
groups = ["test"]
`;

const PIPENV = JSON.stringify({
    _meta: {
        hash: { sha256: 'fake' },
        "pipfile-spec": 6,
        requires: { python_version: '3.12' },
        sources: [{ name: 'pypi', url: 'https://pypi.org/simple', verify_ssl: true }],
    },
    default: {
        iniconfig: { hashes: ['sha256:fake'], markers: "python_version >= '3.10'", version: '==2.3.0' },
        typing_extensions: { hashes: ['sha256:fake'], version: '==4.12.2' },
        'from-git': { git: 'https://github.com/someone/from-git.git', ref: 'abc123' },
        'local-thing': { path: './local-thing', editable: true },
    },
    develop: {
        alabaster: { hashes: ['sha256:fake'], version: '==1.0.0' },
    },
});

describe('discovery', () => {
    test.each([
        ['poetry.lock', 1],
        ['uv.lock', 1],
        ['pdm.lock', 1],
        ['Pipfile.lock', 1],
        ['services/api/poetry.lock', 1],
    ])('%s matches %i parser(s)', (filePath, expected) => {
        expect(findParsersForFile(filePath)).toHaveLength(expected);
    });

    test('it states resolved versions, so its rows win over the manifest', () => {
        expect(parser.resolvesVersions).toBe(true);
    });
});

describe('poetry.lock', () => {
    const deps = read(POETRY, 'poetry.lock');

    test('reads a package at its resolved version', () => {
        expect(deps['appnope']).toBe('0.1.4');
    });

    // PEP 503: the lockfile writes typing_extensions, PyPI serves
    // typing-extensions, and the manifest may spell it either way. Only one
    // spelling can reconcile against a manifest row.
    test('the name is normalised', () => {
        expect(deps['typing-extensions']).toBe('4.12.2');
        expect(deps).not.toHaveProperty('typing_extensions');
    });

    // [package.dependencies] holds that package's own constraints, and each of
    // those packages has a [[package]] element of its own further down. Reading
    // them here would add constraint rows next to resolved ones.
    test('a package.dependencies sub-table is not packages', () => {
        expect(deps).not.toHaveProperty('comm');
        expect(deps).not.toHaveProperty('traitlets');
        expect(deps['ipywidgets']).toBe('8.1.5');
    });

    test('a git source is a dependency with no version to compare', () => {
        expect(deps).toHaveProperty('forked-lib');
        expect(deps['forked-lib']).toBeNull();
    });

    // A directory source is code in this repository, not somebody else's
    // package, so no CVE can ever match it.
    test('a directory source is not a dependency at all', () => {
        expect(deps).not.toHaveProperty('local-thing');
    });

    test('the metadata table is not a package', () => {
        expect(Object.keys(deps).sort()).toEqual([
            'appnope',
            'forked-lib',
            'ipywidgets',
            'typing-extensions',
        ]);
    });
});

describe('uv.lock', () => {
    const deps = read(UV, 'uv.lock');

    test('reads a registry package', () => {
        expect(deps['anyio']).toBe('4.13.0');
        expect(deps['idna']).toBe('3.10');
    });

    // uv writes the project being locked as its own [[package]] with an
    // editable source. It is the repository, not a dependency of it.
    test('the project itself is not a dependency', () => {
        expect(deps).not.toHaveProperty('uv');
    });

    // `dependencies = [{ name = "idna" }, …]` and the requires-dist under
    // [package.metadata] both carry name keys that are not new packages.
    test('an inline dependency list is not packages', () => {
        expect(Object.keys(deps).sort()).toEqual(['anyio', 'from-git', 'idna']);
    });

    test('a git source has no published version', () => {
        expect(deps['from-git']).toBeNull();
    });
});

describe('pdm.lock', () => {
    const deps = read(PDM, 'pdm.lock');

    test('reads every package', () => {
        expect(deps).toEqual({ anyio: '4.13.0', arpeggio: '2.0.3' });
    });

    // PDM puts [metadata] first, and its content_hash and lock_version would
    // otherwise be read as the first package's fields.
    test('a leading metadata table is not a package', () => {
        expect(Object.keys(deps)).toHaveLength(2);
    });

    // These are strings in an array, not [[package]] elements.
    test('the dependencies array is not packages', () => {
        expect(deps).not.toHaveProperty('sniffio');
    });
});

describe('Pipfile.lock', () => {
    const deps = read(PIPENV, 'Pipfile.lock');

    // Pipenv stores "==2.3.0". A version with an operator in front of it does
    // not compare against PyPI's answer, and comparing is the point.
    test('the == comes off the version', () => {
        expect(deps['iniconfig']).toBe('2.3.0');
    });

    test('the name is normalised', () => {
        expect(deps['typing-extensions']).toBe('4.12.2');
    });

    // A dev dependency runs in CI and in a developer's container, which is
    // still exposure.
    test('develop counts as well as default', () => {
        expect(deps['alabaster']).toBe('1.0.0');
    });

    test('a git entry has no published version', () => {
        expect(deps['from-git']).toBeNull();
    });

    test('a path entry is not a dependency', () => {
        expect(deps).not.toHaveProperty('local-thing');
    });

    test('_meta is not packages', () => {
        expect(deps).not.toHaveProperty('pypi');
        expect(Object.keys(deps).sort()).toEqual([
            'alabaster',
            'from-git',
            'iniconfig',
            'typing-extensions',
        ]);
    });
});

describe('normalizePythonName', () => {
    test.each([
        ['typing_extensions', 'typing-extensions'],
        ['Typing.Extensions', 'typing-extensions'],
        ['zope.interface', 'zope-interface'],
        ['ruamel--yaml__clib', 'ruamel-yaml-clib'],
        ['requests', 'requests'],
    ])('%s becomes %s', (input, expected) => {
        expect(normalizePythonName(input)).toBe(expected);
    });
});

describe('what must not throw', () => {
    test.each([
        ['poetry.lock', '# nothing here\n'],
        ['uv.lock', 'version = 1\n'],
        ['pdm.lock', '[metadata]\nlock_version = "4.5.0"\n'],
        ['Pipfile.lock', 'not json'],
        ['Pipfile.lock', '{}'],
    ])('%s: %s', (file, content) => {
        expect(parser.parse(content, file)).toEqual([]);
    });
});
