import { describe, test, expect } from '@jest/globals';

const manifest = await import('#app/infrastructure/parsers/pubParser.js');
const lock = await import('#app/infrastructure/parsers/pubLockParser.js');
const { findParsersForFile } = await import('#app/infrastructure/parsers/parserRegistry.js');

// Trimmed from flutter/gallery. The shapes that matter are the four an entry
// can take: a bare constraint, an SDK, a path, and a git repository.
const PUBSPEC = `name: gallery
description: A resource to help developers evaluate Flutter.
version: 2.10.3+021003

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.2
  google_fonts: "6.1.0"
  # a comment inside the section
  my_lib:
    path: ../my_lib
  forked_thing:
    git:
      url: https://github.com/org/forked_thing.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

dependency_overrides:
  meta: 1.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
`;

const PUBSPEC_LOCK = `# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  animations:
    dependency: "direct main"
    description:
      name: animations
      sha256: "d3d6dcfb218225bbe68e87ccf6378bbb2e32a94900722c5f81611dad089911cb"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.10"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  my_lib:
    dependency: "direct main"
    description:
      path: "../my_lib"
      relative: true
    source: path
    version: "0.1.0"
  forked_thing:
    dependency: "direct main"
    description:
      path: "."
      ref: main
      resolved-ref: "8a0f2ec2f2b9ffb4f0b0c1e7c3c2a1d4e5f60718"
      url: "https://github.com/org/forked_thing.git"
    source: git
    version: "1.2.3"
sdks:
  dart: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"
`;

describe('discovery', () => {
    test.each([
        ['pubspec.yaml', 1],
        ['pubspec.lock', 1],
        ['packages/ui/pubspec.yaml', 1],
        ['pubspec.yaml.bak', 0],
    ])('%s matches %i parser(s)', (filePath, expected) => {
        expect(findParsersForFile(filePath)).toHaveLength(expected);
    });

    // pubspec.lock is what states the version in the build; pubspec.yaml only
    // constrains it. See reconcileDependencies.js.
    test('only the lockfile claims to resolve versions', () => {
        expect(lock.resolvesVersions).toBe(true);
        expect(manifest.resolvesVersions).toBeUndefined();
    });
});

describe('pubspec.yaml', () => {
    const deps = manifest.parse(PUBSPEC, 'pubspec.yaml');
    const byName = name => deps.find(dependency => dependency.name === name);

    test('reads a bare constraint', () => {
        expect(byName('animations')).toMatchObject({
            ecosystem: 'PUB',
            version: '^2.0.2',
            manifestFile: 'pubspec.yaml',
        });
    });

    test('a quoted version loses only the quotes', () => {
        expect(byName('google_fonts').version).toBe('6.1.0');
    });

    test('dev_dependencies count', () => {
        expect(byName('build_runner').version).toBe('^2.4.6');
    });

    test.each(['flutter', 'flutter_localizations', 'flutter_test', 'my_lib', 'forked_thing'])(
        '%s opens a nested map, so it has no version rather than a made-up one',
        name => {
            expect(byName(name)).toMatchObject({ version: null });
        }
    );

    describe('what is not a dependency', () => {
        // Reading these would file the project as depending on itself.
        test.each(['gallery', 'version', 'description'])('the package\'s own %s', name => {
            expect(byName(name)).toBeUndefined();
        });

        // environment: holds the SDK bounds, not packages. The trap is that
        // `flutter:` appears there and again as a real dependency.
        test('the sdk bound under environment', () => {
            expect(deps.filter(d => d.name === 'flutter')).toHaveLength(1);
        });

        test('the flutter: build section at the end', () => {
            expect(byName('uses-material-design')).toBeUndefined();
            expect(byName('assets')).toBeUndefined();
        });

        // An override restates a dependency declared above; counting it would
        // be counting the same package twice.
        test('a dependency_overrides entry', () => {
            expect(byName('meta')).toBeUndefined();
        });
    });
});

describe('pubspec.lock', () => {
    const deps = lock.parse(PUBSPEC_LOCK, 'pubspec.lock');
    const byName = name => deps.find(dependency => dependency.name === name);

    test('reads a hosted package at its resolved version', () => {
        expect(byName('animations')).toMatchObject({
            ecosystem: 'PUB',
            version: '2.0.10',
            manifestFile: 'pubspec.lock',
        });
    });

    // Most of a Flutter application's surface arrives transitively, and a CVE
    // does not care how a package got into the build.
    test('a transitive package counts', () => {
        expect(byName('async')).toMatchObject({ version: '2.11.0' });
    });

    test.each([
        ['flutter', 'sdk'],
        ['my_lib', 'path'],
        ['forked_thing', 'git'],
    ])('%s comes from a %s source, so its version is not one pub.dev can answer', name => {
        expect(byName(name)).toMatchObject({ version: null });
    });

    test('the sdks section at the end is not packages', () => {
        expect(deps.map(d => d.name)).not.toContain('dart');
        expect(deps).toHaveLength(5);
    });

    test('no sha256 or url line becomes a package', () => {
        expect(deps.map(d => d.name).sort()).toEqual([
            'animations',
            'async',
            'flutter',
            'forked_thing',
            'my_lib',
        ]);
    });
});

describe('what must not throw', () => {
    test.each([
        ['an empty file', ''],
        ['a pubspec with no dependencies at all', 'name: bare\nversion: 1.0.0\n'],
        ['a lockfile with no packages section', '# Generated by pub\nsdks:\n  dart: ">=3.0.0"\n'],
    ])('%s', (_label, content) => {
        expect(manifest.parse(content, 'pubspec.yaml')).toEqual([]);
        expect(lock.parse(content, 'pubspec.lock')).toEqual([]);
    });
});
